apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/saeedgebaly/cloud-native-devops-platform-
    targetRevision: prod
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
