apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saeedgebaly/cloud-native-devops-platform-
    targetRevision: staging
    path: helm/auth-service
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy: {}
