apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saeedgebaly/cloud-native-devops-platform-
    targetRevision: main
    path: helm/core-service

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
